const axios = require("axios");

/*
|--------------------------------------------------------------------------
| SMTP2GO Configuration
|--------------------------------------------------------------------------
|
| Required .env variables:
|
| SMTP2GO_API_KEY=your_smtp2go_api_key
| ALERT_EMAIL_FROM=your_verified_sender_email
| ALERT_EMAIL_TO=recipient_email
|
|--------------------------------------------------------------------------
*/

const SMTP2GO_API_URL =
  "https://api.smtp2go.com/v3/email/send";

/*
|--------------------------------------------------------------------------
| Send Alert Email
|--------------------------------------------------------------------------
*/

const sendAlertEmail = async (alert) => {
  try {
    /*
    |--------------------------------------------------------------------------
    | Validate SMTP2GO API Key
    |--------------------------------------------------------------------------
    */

    if (!process.env.SMTP2GO_API_KEY) {
      throw new Error(
        "SMTP2GO_API_KEY is missing from .env"
      );
    }

    /*
    |--------------------------------------------------------------------------
    | Validate Sender Email
    |--------------------------------------------------------------------------
    */

    if (!process.env.ALERT_EMAIL_FROM) {
      throw new Error(
        "ALERT_EMAIL_FROM is missing from .env"
      );
    }

    /*
    |--------------------------------------------------------------------------
    | Validate Receiver Email
    |--------------------------------------------------------------------------
    */

    if (!process.env.ALERT_EMAIL_TO) {
      throw new Error(
        "ALERT_EMAIL_TO is missing from .env"
      );
    }

    /*
    |--------------------------------------------------------------------------
    | Validate Alert Data
    |--------------------------------------------------------------------------
    */

    if (!alert) {
      throw new Error(
        "Alert data is required."
      );
    }

    /*
    |--------------------------------------------------------------------------
    | Prepare Email
    |--------------------------------------------------------------------------
    */

    const subject =
      `[${alert.level || "Alert"}] ${
        alert.title || "Flood Alert"
      }`;

    const textBody = `
Flood Early Warning System
========================================

ALERT DETAILS

Alert ID:
${alert.id || "N/A"}

Alert:
${alert.title || "N/A"}

Level:
${alert.level || "N/A"}

Status:
${alert.status || "Active"}

Source:
${alert.source || "Unknown"}

Location:
${alert.location || "N/A"}

Monitoring Station:
${alert.station || "N/A"}

Description:
${alert.description || "N/A"}

Time:
${alert.timestamp || new Date().toLocaleString()}

========================================

This alert was generated by the
Flood Early Warning System.

Please check the monitoring dashboard
for more information.

========================================
`.trim();

    /*
    |--------------------------------------------------------------------------
    | SMTP2GO Request
    |--------------------------------------------------------------------------
    */

    const response = await axios.post(
      SMTP2GO_API_URL,

      {
        api_key:
          process.env.SMTP2GO_API_KEY,

        sender:
          process.env.ALERT_EMAIL_FROM,

        to: [
          process.env.ALERT_EMAIL_TO,
        ],

        subject,

        text_body: textBody,
      },

      {
        headers: {
          "Content-Type":
            "application/json",

          Accept:
            "application/json",
        },

        timeout: 15000,
      }
    );

    /*
    |--------------------------------------------------------------------------
    | Success
    |--------------------------------------------------------------------------
    */

    console.log(
      "========================================"
    );

    console.log(
      "ALERT EMAIL SENT SUCCESSFULLY"
    );

    console.log(
      "SMTP2GO Response:",
      response.data
    );

    console.log(
      "========================================"
    );

    return {
      success: true,

      message:
        "Alert email sent successfully.",

      data: response.data,
    };
  } catch (error) {
    /*
    |--------------------------------------------------------------------------
    | Error Handling
    |--------------------------------------------------------------------------
    */

    const errorData =
      error.response?.data ||
      error.message ||
      "Unknown SMTP2GO error";

    console.error(
      "========================================"
    );

    console.error(
      "SMTP2GO ALERT EMAIL FAILED"
    );

    console.error(
      "Error:",
      errorData
    );

    console.error(
      "========================================"
    );

    return {
      success: false,

      message:
        "Failed to send alert email.",

      error: errorData,
    };
  }
};

/*
|--------------------------------------------------------------------------
| Export
|--------------------------------------------------------------------------
*/

module.exports = {
  sendAlertEmail,
};