const axios = require("axios");
const pool = require("../config/db");

const SMTP2GO_API_URL =
  "https://api.smtp2go.com/v3/email/send";

const sendAlertEmail = async (alert) => {
  try {
    /*
    |--------------------------------------------------------------------------
    | Validate SMTP2GO Configuration
    |--------------------------------------------------------------------------
    */

    if (!process.env.SMTP2GO_API_KEY) {
      throw new Error("SMTP2GO_API_KEY is missing from .env");
    }

    if (!process.env.ALERT_EMAIL_FROM) {
      throw new Error("ALERT_EMAIL_FROM is missing from .env");
    }

    if (!alert) {
      throw new Error("Alert data is required.");
    }

    /*
    |--------------------------------------------------------------------------
    | Get Active Users
    |--------------------------------------------------------------------------
    */

    const usersResult = await pool.query(`
      SELECT email
      FROM users
      WHERE status = 'active'
        AND email IS NOT NULL
        AND email <> ''
    `);

    const recipientEmails = usersResult.rows.map(
      (user) => user.email
    );

    if (recipientEmails.length === 0) {
      throw new Error(
        "No active users with valid email addresses found."
      );
    }

    /*
    |--------------------------------------------------------------------------
    | Prepare Email
    |--------------------------------------------------------------------------
    */

    const subject =
      `[${alert.level || "Alert"}] ${
        alert.title || "Flood Alert"
      }`;

    const textBody = `
Flood Early Warning System
========================================

ALERT DETAILS

Alert ID:
${alert.id || "N/A"}

Alert:
${alert.title || "N/A"}

Level:
${alert.level || "N/A"}

Status:
${alert.status || "Active"}

Source:
${alert.source || "Unknown"}

Location:
${alert.location || "N/A"}

Monitoring Station:
${alert.station || "N/A"}

Description:
${alert.description || "N/A"}

Time:
${alert.created_at || new Date().toLocaleString()}

========================================

This alert was generated by the
Flood Early Warning System.

Please check the monitoring dashboard
for more information.

========================================
`.trim();

    /*
    |--------------------------------------------------------------------------
    | Send Email Through SMTP2GO
    |--------------------------------------------------------------------------
    */

    const response = await axios.post(
      SMTP2GO_API_URL,
      {
        api_key: process.env.SMTP2GO_API_KEY,

        sender: process.env.ALERT_EMAIL_FROM,

        to: recipientEmails,

        subject,

        text_body: textBody,
      },
      {
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },

        timeout: 15000,
      }
    );

    /*
    |--------------------------------------------------------------------------
    | Success
    |--------------------------------------------------------------------------
    */

    console.log("========================================");
    console.log("ALERT EMAIL SENT SUCCESSFULLY");
    console.log(
      "Recipients:",
      recipientEmails
    );
    console.log(
      "SMTP2GO Response:",
      response.data
    );
    console.log("========================================");

    return {
      success: true,
      message: "Alert email sent successfully.",
      recipients: recipientEmails,
      data: response.data,
    };

  } catch (error) {

    const errorData =
      error.response?.data ||
      error.message ||
      "Unknown SMTP2GO error";

    console.error("========================================");
    console.error("SMTP2GO ALERT EMAIL FAILED");
    console.error("Error:", errorData);
    console.error("========================================");

    return {
      success: false,
      message: "Failed to send alert email.",
      error: errorData,
    };
  }
};

module.exports = {
  sendAlertEmail,
};